[tox]
envlist = py314, lint, type
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-qt
    PySide6
commands =
    pytest {posargs:tests}

[testenv:lint]
description = Run Ruff checks
skip_install = true
deps =
    ruff
commands =
    ruff check src tests

[testenv:type]
description = Run Pyright
deps =
    pyright
    pytest
    PySide6
commands =
    pyright src tests
