[tox]
envlist = py314
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps =
    ruff
    pyright
    PySide6-stubs
    pytest
commands =
    ruff check src tests
    pyright src
    pytest tests
