name: Windows application

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r pyinstaller/requirements.txt
    - name: Build resources
      run: |
        pyrcc5 pyinstaller/table_control.qrc -o src/table_control/_resources.py
    - name: Build with pyinstaller
      run: |
        pyinstaller ./pyinstaller/windows_app.spec
    - name: Calculate hashsums
      shell: bash
      run: |
        cd dist
        for f in $(find . -name 'table-control-*.exe'); do
          sha1sum $(basename $f) > $f.sha1
          sha256sum $(basename $f) > $f.sha256
        done
    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: table-control-artifact
        path: |
          dist/table-control-*.exe
          dist/table-control-*.exe.sha*
